name: animated_gradient_border
description: "An easily customizable, animated gradient border widget for Flutter."
version: 0.1.0
homepage: https://github.com/ervindobri/
repository: https://github.com/ervindobri/animated_gradient_border
issue_tracker: https://github.com/ervindobri/animated_gradient_border/issues
topics:
  - flutter
  - widget
  - animation
  - gradient
  - border

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: "animated_gradient_border example"
    path: screenshots/preview.gif
